// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiykxoCFVYhM-87IgY3aW7i7O7dglK5Uo',
    appId: '1:216173815010:web:54485459c62b2175ee2abb',
    messagingSenderId: '216173815010',
    projectId: 'hakan-bogan',
    authDomain: 'hakan-bogan.firebaseapp.com',
    storageBucket: 'hakan-bogan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCloS1FuqNqpBJieS5KYW5zXhXg4ew920',
    appId: '1:216173815010:android:a58ed86822867ea7ee2abb',
    messagingSenderId: '216173815010',
    projectId: 'hakan-bogan',
    storageBucket: 'hakan-bogan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-hN2-HI2lPVAIHV5Oc6HeXY7Y3F-NOvI',
    appId: '1:216173815010:ios:3de967a88266a5a7ee2abb',
    messagingSenderId: '216173815010',
    projectId: 'hakan-bogan',
    storageBucket: 'hakan-bogan.appspot.com',
    iosClientId: '216173815010-3rb2e0098q6n3ksj7eg2rqnajbpo548n.apps.googleusercontent.com',
    iosBundleId: 'com.hakanbogan.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-hN2-HI2lPVAIHV5Oc6HeXY7Y3F-NOvI',
    appId: '1:216173815010:ios:3de967a88266a5a7ee2abb',
    messagingSenderId: '216173815010',
    projectId: 'hakan-bogan',
    storageBucket: 'hakan-bogan.appspot.com',
    iosClientId: '216173815010-3rb2e0098q6n3ksj7eg2rqnajbpo548n.apps.googleusercontent.com',
    iosBundleId: 'com.hakanbogan.mynotes',
  );
}
